export const SIGNIN = "SIGNIN"
export const SIGNOUT = "SIGNOUT"
export const ADD_SITE = "ADD_SITE"
export const DATA_SITE = "DATA_SITE"
export const EDIT_SITE = "EDIT_SITE"
export const REMOVE_SITE = "REMOVE_SITE"
